# lint-every-push.yml

name: 'lint-every-push'

# workflow를 동작하게하는 trigger
# repository에 push 이벤트가 발생할 때마다 실행
on: push

jobs:
  test:
    name: Lint Every Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - run: yarn lint
